-- ============================================
-- KAPADOKYA CAFE & RESTAURANT
-- COMPLETE DATABASE MIGRATION
-- Supabase Dashboard SQL Editor'a yapıştırın
-- ============================================

-- STEP 1: Clean up existing schema
-- ============================================
DROP TABLE IF EXISTS public.daily_ledger CASCADE;
DROP VIEW IF EXISTS public.daily_ledger CASCADE;
DROP TABLE IF EXISTS public.expenses CASCADE;
DROP TABLE IF EXISTS public.daily_income CASCADE;
DROP TABLE IF EXISTS public.expense_categories CASCADE;
DROP TABLE IF EXISTS public.income_types CASCADE;
DROP TABLE IF EXISTS public.income_sources CASCADE;
DROP TABLE IF EXISTS public.income_transactions CASCADE;
DROP FUNCTION IF EXISTS get_total_income(DATE, DATE);
DROP FUNCTION IF EXISTS get_total_expense(DATE, DATE);
DROP FUNCTION IF EXISTS get_profit_loss(DATE, DATE);
DROP FUNCTION IF EXISTS get_daily_summary(DATE);
DROP FUNCTION IF EXISTS update_updated_at_column();

-- STEP 2: Create Expense Categories Table
-- ============================================
CREATE TABLE public.expense_categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  parent_id BIGINT REFERENCES expense_categories(id) ON DELETE SET NULL,
  description TEXT,
  order_index INT DEFAULT 0
);

-- Insert main expense categories (Germany-specific)
INSERT INTO public.expense_categories (name, description, order_index) VALUES
  ('Malzeme Giderleri', 'Tüm malzeme ve gıda alımları', 1),
  ('Kira ve Nebenkosten', 'Kira ve yan giderler', 2),
  ('Elektrik', 'Elektrik faturası', 3),
  ('Doğalgaz', 'Doğalgaz faturası', 4),
  ('Su', 'Su faturası', 5),
  ('Personel', 'Personel maaşları', 6),
  ('Personel Sigorta', 'Personel sigorta ödemeleri', 7),
  ('Vergi', 'Vergi ödemeleri', 8),
  ('Muhasebe', 'Muhasebe ofisi ücretleri', 9),
  ('Diğer Giderler', 'Diğer çeşitli giderler', 10);

-- Insert subcategories for 'Malzeme Giderleri'
INSERT INTO public.expense_categories (name, parent_id, description, order_index) 
SELECT 
  name,
  (SELECT id FROM expense_categories WHERE name = 'Malzeme Giderleri'),
  description,
  order_index
FROM (VALUES
  ('Döner', 'Döner alımları', 1),
  ('Kuzu', 'Kuzu eti alımları', 2),
  ('Tavuk', 'Tavuk eti alımları', 3),
  ('Diğer Et Gıdası', 'Dil, işkembe vb. et ürünleri', 4),
  ('Kuru Gıda ve Çay', 'Kuru gıda, baharatlar, çay', 5),
  ('İçecek', 'İçecek alımları', 6),
  ('Sebze', 'Sebze ve meyve alımları', 7)
) AS subcategories(name, description, order_index);

-- STEP 3: Create Expenses Table
-- ============================================
CREATE TABLE public.expenses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_id BIGINT REFERENCES expense_categories(id) ON DELETE SET NULL,
  amount NUMERIC(12,2) NOT NULL,
  description TEXT,
  expense_date DATE NOT NULL DEFAULT CURRENT_DATE,
  invoice_number TEXT,
  vendor TEXT,
  payment_method TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_expenses_date ON public.expenses(expense_date DESC);
CREATE INDEX idx_expenses_category ON public.expenses(category_id);

-- STEP 4: Create NEW Income Model (Transactional)
-- ============================================

-- Income Sources Table (Lieferando, Uber Eats, etc.)
CREATE TABLE public.income_sources (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Insert default income sources (Germany-specific)
INSERT INTO public.income_sources (name, description) VALUES
('Lieferando', 'Online-Bestellungen über Lieferando'),
('Uber Eats', 'Online-Bestellungen über Uber Eats'),
('Wolt', 'Online-Bestellungen über Wolt'),
('Bar/Tisch Verkauf', 'Direkte Verkäufe im Restaurant (Bar/Tisch)'),
('Abholung', 'Kunden holen Bestellungen selbst ab'),
('Catering/Events', 'Catering und private Veranstaltungen'),
('Sonstige Einnahmen', 'Andere Einnahmequellen');

-- Income Transactions Table (Each individual transaction)
CREATE TABLE public.income_transactions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    source_id UUID REFERENCES public.income_sources(id) ON DELETE SET NULL,
    amount NUMERIC(10, 2) NOT NULL,
    description TEXT,
    transaction_date DATE NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_income_transactions_date ON public.income_transactions(transaction_date DESC);
CREATE INDEX idx_income_transactions_source ON public.income_transactions(source_id);

-- STEP 5: Create Helper Functions
-- ============================================

-- Updated_at auto-update trigger function
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
   NEW.updated_at = NOW();
   RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Apply triggers
CREATE TRIGGER update_expenses_updated_at BEFORE UPDATE ON public.expenses
FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_income_sources_updated_at BEFORE UPDATE ON public.income_sources
FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- Daily summary function for "Gün Sonu" reports
CREATE OR REPLACE FUNCTION get_daily_summary(summary_date DATE)
RETURNS TABLE(total_income NUMERIC, total_expense NUMERIC, net_profit NUMERIC) AS $$
BEGIN
    RETURN QUERY
    SELECT
        COALESCE(SUM(it.amount), 0) AS total_income,
        (SELECT COALESCE(SUM(e.amount), 0) FROM public.expenses e WHERE e.expense_date = summary_date) AS total_expense,
        COALESCE(SUM(it.amount), 0) - (SELECT COALESCE(SUM(e.amount), 0) FROM public.expenses e WHERE e.expense_date = summary_date) AS net_profit
    FROM
        public.income_transactions it
    WHERE
        it.transaction_date = summary_date;
END;
$$ LANGUAGE plpgsql;

-- Date range functions
CREATE OR REPLACE FUNCTION get_total_income(start_date DATE, end_date DATE)
RETURNS NUMERIC AS $$
  SELECT COALESCE(SUM(amount), 0)
  FROM public.income_transactions
  WHERE transaction_date BETWEEN start_date AND end_date;
$$ LANGUAGE SQL;

CREATE OR REPLACE FUNCTION get_total_expense(start_date DATE, end_date DATE)
RETURNS NUMERIC AS $$
  SELECT COALESCE(SUM(amount), 0)
  FROM public.expenses
  WHERE expense_date BETWEEN start_date AND end_date;
$$ LANGUAGE SQL;

CREATE OR REPLACE FUNCTION get_profit_loss(start_date DATE, end_date DATE)
RETURNS NUMERIC AS $$
  SELECT get_total_income(start_date, end_date) - get_total_expense(start_date, end_date);
$$ LANGUAGE SQL;

-- STEP 6: Create Daily Ledger View
-- ============================================
CREATE OR REPLACE VIEW public.daily_ledger AS
WITH all_dates AS (
    SELECT DISTINCT transaction_date AS entry_date FROM public.income_transactions
    UNION
    SELECT DISTINCT expense_date AS entry_date FROM public.expenses
),
daily_incomes AS (
    SELECT
        transaction_date,
        sum(amount) as total
    FROM public.income_transactions
    GROUP BY transaction_date
),
daily_expenses AS (
    SELECT
        expense_date,
        sum(amount) as total
    FROM public.expenses
    GROUP BY expense_date
)
SELECT
    d.entry_date,
    COALESCE(di.total, 0) as income,
    COALESCE(de.total, 0) as expense,
    (COALESCE(di.total, 0) - COALESCE(de.total, 0)) as balance
FROM all_dates d
LEFT JOIN daily_incomes di ON d.entry_date = di.transaction_date
LEFT JOIN daily_expenses de ON d.entry_date = de.expense_date
ORDER BY d.entry_date DESC;

-- STEP 7: Enable Row Level Security (RLS)
-- ============================================

-- Enable RLS on all tables
ALTER TABLE public.expense_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.expenses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.income_sources ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.income_transactions ENABLE ROW LEVEL SECURITY;

-- DEV POLICIES: Allow anonymous access for development
-- IMPORTANT: Replace with auth policies in production

CREATE POLICY "Dev allow all on expense_categories" ON public.expense_categories
  FOR ALL USING (true) WITH CHECK (true);

CREATE POLICY "Dev allow all on expenses" ON public.expenses
  FOR ALL USING (true) WITH CHECK (true);

CREATE POLICY "Dev allow all on income_sources" ON public.income_sources
  FOR ALL USING (true) WITH CHECK (true);

CREATE POLICY "Dev allow all on income_transactions" ON public.income_transactions
  FOR ALL USING (true) WITH CHECK (true);

-- ============================================
-- MIGRATION COMPLETE!
-- ============================================
-- Yeni sistem artık hazır:
-- 1. expense_categories - Gider kategorileri
-- 2. expenses - Gider kayıtları
-- 3. income_sources - Gelir kaynakları (Lieferando, Uber Eats, etc.)
-- 4. income_transactions - Her bir gelir işlemi
-- 5. daily_ledger - Günlük özet view
-- 6. get_daily_summary() - Gün sonu raporu fonksiyonu
-- ============================================
