#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import { parse } from 'csv-parse/sync';

function usageAndExit() {
  console.error('Usage: node scripts/menu_csv_to_sql.mjs <input.csv> <output.sql>');
  process.exit(1);
}

if (process.argv.length < 4) {
  usageAndExit();
}

const inputPath = path.resolve(process.argv[2]);
const outputPath = path.resolve(process.argv[3]);

if (!fs.existsSync(inputPath)) {
  console.error(`Input file not found: ${inputPath}`);
  process.exit(1);
}

const csvRaw = fs.readFileSync(inputPath, 'utf8');

const records = parse(csvRaw, {
  columns: true,
  skip_empty_lines: true,
  trim: true,
});

function esc(str) {
  if (str === null || str === undefined) return null;
  return String(str).replace(/'/g, "''");
}

function parsePrice(eur) {
  if (!eur) return null;
  const cleaned = eur.replace(/€/g, '').replace(/\s/g, '').replace(/\./g, '').replace(/,/g, '.');
  const val = parseFloat(cleaned);
  return Number.isFinite(val) ? val : null;
}

function extractNames(name) {
  if (!name) return { name_tr: null, name_de: null };
  const m = name.match(/^(.+?)\s*\((.+)\)\s*$/);
  if (m) {
    return { name_tr: m[1].trim(), name_de: m[2].trim() };
  }
  return { name_tr: name, name_de: name };
}

function parseAllergenCodes(text) {
  if (!text) return [];
  const codes = new Set();
  const regex = /(^|[;\s,])([a-zA-Z0-9]+)\s*:/g;
  let m;
  while ((m = regex.exec(text)) !== null) {
    const code = (m[2] || '').trim().toLowerCase();
    if (code) codes.add(code);
  }
  return Array.from(codes);
}

// Maintain category order as they appear
const categories = [];
const categoryIndex = new Map();

for (const row of records) {
  const cat = row['Kategori']?.trim();
  if (!cat) continue;
  if (!categoryIndex.has(cat)) {
    categoryIndex.set(cat, categories.length);
    categories.push({ name_de: cat });
  }
}

// Build position counters per category for dish ordering
const dishPosByCat = new Map();
function nextDishPosition(catName) {
  const curr = dishPosByCat.get(catName) || 0;
  const next = curr + 1;
  dishPosByCat.set(catName, next);
  return next;
}

let sql = '';
sql += '-- Generated by scripts/menu_csv_to_sql.mjs\n';
sql += 'BEGIN;\n\n';

// Insert categories if not existing (assumes default id)
sql += '-- Upsert categories from CSV (by name_de)\n';
categories.forEach((c, idx) => {
  const pos = idx + 1;
  sql += `INSERT INTO public.dish_categories (name_de, position, is_active)\n`;
  sql += `SELECT '${esc(c.name_de)}', ${pos}, true\n`;
  sql += `WHERE NOT EXISTS (SELECT 1 FROM public.dish_categories WHERE name_de='${esc(c.name_de)}');\n`;
});
sql += '\n';

// Insert dishes
sql += '-- Insert dishes parsed from CSV\n';
for (const row of records) {
  const category = row['Kategori']?.trim();
  const menuNumber = (row['Numara'] ?? '').toString().trim();
  const nameRaw = row['İsim'] ?? row['Isim'] ?? row['İSİM'] ?? '';
  const priceRaw = row['Fiyat'] ?? '';
  const details = row['Aciklamalar'] ?? row['Açiklamalar'] ?? row['Açıklamalar'] ?? '';

  if (!category || !nameRaw) continue;

  const { name_tr, name_de } = extractNames(String(nameRaw).trim());
  const price = parsePrice(String(priceRaw));
  const codes = parseAllergenCodes(String(details));
  const position = nextDishPosition(category);

  const codesSql = codes.length ? `ARRAY[${codes.map(c => `'${esc(c)}'`).join(', ')}]` : `'{}'`;

  sql += `INSERT INTO public.dishes (category_id, menu_number, name_de, name_tr, price, description_de, description_tr, ingredients, raw_details, allergen_codes, is_active, position)\n`;
  sql += `VALUES (\n`;
  sql += `  (SELECT id FROM public.dish_categories WHERE name_de='${esc(category)}' LIMIT 1),\n`;
  sql += `  ${menuNumber ? `'${esc(menuNumber)}'` : 'NULL'},\n`;
  sql += `  ${name_de ? `'${esc(name_de)}'` : 'NULL'},\n`;
  sql += `  ${name_tr ? `'${esc(name_tr)}'` : 'NULL'},\n`;
  sql += `  ${Number.isFinite(price) ? price.toFixed(2) : 'NULL'},\n`;
  sql += `  NULL,\n`;
  sql += `  NULL,\n`;
  sql += `  NULL,\n`;
  sql += `  ${details ? `'${esc(details)}'` : 'NULL'},\n`;
  sql += `  ${codesSql},\n`;
  sql += `  true,\n`;
  sql += `  ${position}\n`;
  sql += `);\n`;
}

sql += '\nCOMMIT;\n';

fs.writeFileSync(outputPath, sql, 'utf8');
console.log(`SQL written to ${outputPath}`);
