-- ============================================
-- RESET SCHEMA (for development)
-- ============================================
DROP TABLE IF EXISTS daily_ledger CASCADE;
DROP TABLE IF EXISTS expenses CASCADE;
DROP TABLE IF EXISTS daily_income CASCADE;
DROP TABLE IF EXISTS expense_categories CASCADE;
DROP TABLE IF EXISTS income_types CASCADE;

-- ============================================
-- KAPADOKYA CAFE & RESTAURANT
-- Muhasebe ve Yönetim Sistemi
-- ============================================

-- 1. Gelir Kategorileri (Income Types)
CREATE TABLE income_types (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  description TEXT
);

-- Gelir kategorilerini ekle
INSERT INTO income_types (name, description) VALUES
  ('Nakit', 'Nakit ödeme'),
  ('Kredi Kartı', 'Kredi kartı ile ödeme'),
  ('Lieferando', 'Lieferando online sipariş');

-- 2. Günlük Gelir Kayıtları (Daily Income Records)
CREATE TABLE daily_income (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date DATE NOT NULL DEFAULT CURRENT_DATE,
  nakit NUMERIC(12,2) DEFAULT 0,
  kredi_karti NUMERIC(12,2) DEFAULT 0,
  lieferando NUMERIC(12,2) DEFAULT 0,
  toplam NUMERIC(12,2) GENERATED ALWAYS AS (nakit + kredi_karti + lieferando) STORED,
  notlar TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(date)
);

-- 3. Gider Kategorileri (Expense Categories)
CREATE TABLE expense_categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  parent_id BIGINT REFERENCES expense_categories(id) ON DELETE SET NULL,
  description TEXT,
  order_index INT DEFAULT 0
);

-- Ana gider kategorilerini ekle
INSERT INTO expense_categories (name, description, order_index) VALUES
  ('Malzeme Giderleri', 'Tüm malzeme ve gıda alımları', 1),
  ('Kira ve Nebenkosten', 'Kira ve yan giderler', 2),
  ('Elektrik', 'Elektrik faturası', 3),
  ('Doğalgaz', 'Doğalgaz faturası', 4),
  ('Su', 'Su faturası', 5),
  ('Personel', 'Personel maaşları', 6),
  ('Personel Sigorta', 'Personel sigorta ödemeleri', 7),
  ('Vergi', 'Vergi ödemeleri', 8),
  ('Muhasebe', 'Muhasebe ofisi ücretleri', 9),
  ('Diğer Giderler', 'Diğer çeşitli giderler', 10);

-- Malzeme Giderleri alt kategorileri
INSERT INTO expense_categories (name, parent_id, description, order_index) 
SELECT 
  name,
  (SELECT id FROM expense_categories WHERE name = 'Malzeme Giderleri'),
  description,
  order_index
FROM (VALUES
  ('Döner', 'Döner alımları', 1),
  ('Kuzu', 'Kuzu eti alımları', 2),
  ('Tavuk', 'Tavuk eti alımları', 3),
  ('Diğer Et Gıdası', 'Dil, işkembe vb. et ürünleri', 4),
  ('Kuru Gıda ve Çay', 'Kuru gıda, baharatlar, çay', 5),
  ('İçecek', 'İçecek alımları', 6),
  ('Sebze', 'Sebze ve meyve alımları', 7)
) AS subcategories(name, description, order_index);

-- 4. Giderler Tablosu (Expenses)
CREATE TABLE expenses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_id BIGINT REFERENCES expense_categories(id) ON DELETE SET NULL,
  amount NUMERIC(12,2) NOT NULL,
  description TEXT,
  expense_date DATE NOT NULL DEFAULT CURRENT_DATE,
  invoice_number TEXT,
  vendor TEXT,
  payment_method TEXT, -- Nakit, Havale, Kredi Kartı
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Günlük Kasa Özeti (Daily Ledger)
CREATE TABLE daily_ledger (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date DATE NOT NULL UNIQUE,
  opening_balance NUMERIC(12,2) NOT NULL DEFAULT 0,
  total_income NUMERIC(12,2) DEFAULT 0,
  total_expense NUMERIC(12,2) DEFAULT 0,
  closing_balance NUMERIC(12,2) GENERATED ALWAYS AS (opening_balance + total_income - total_expense) STORED,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================
-- INDEXES (Performans için)
-- ============================================

CREATE INDEX idx_daily_income_date ON daily_income(date DESC);
CREATE INDEX idx_expenses_date ON expenses(expense_date DESC);
CREATE INDEX idx_expenses_category ON expenses(category_id);
CREATE INDEX idx_daily_ledger_date ON daily_ledger(date DESC);

-- ============================================
-- TRIGGERS (Otomatik güncellemeler)
-- ============================================

-- Updated_at otomatik güncelleme fonksiyonu
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
   NEW.updated_at = NOW();
   RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Triggers
CREATE TRIGGER update_daily_income_updated_at BEFORE UPDATE ON daily_income
FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_expenses_updated_at BEFORE UPDATE ON expenses
FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_daily_ledger_updated_at BEFORE UPDATE ON daily_ledger
FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ============================================
-- ROW LEVEL SECURITY (Güvenlik)
-- ============================================

-- RLS'i etkinleştir
ALTER TABLE daily_income ENABLE ROW LEVEL SECURITY;
ALTER TABLE expenses ENABLE ROW LEVEL SECURITY;
ALTER TABLE expense_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE daily_ledger ENABLE ROW LEVEL SECURITY;

-- Admin kullanıcılar için policy (authenticated kullanıcılar tüm işlemleri yapabilir)
CREATE POLICY "Admin users can do everything on daily_income" ON daily_income
  FOR ALL USING (auth.role() = 'authenticated');

CREATE POLICY "Admin users can do everything on expenses" ON expenses
  FOR ALL USING (auth.role() = 'authenticated');

CREATE POLICY "Everyone can read expense_categories" ON expense_categories
  FOR SELECT USING (true);

CREATE POLICY "Admin users can modify expense_categories" ON expense_categories
  FOR ALL USING (auth.role() = 'authenticated');

CREATE POLICY "Admin users can do everything on daily_ledger" ON daily_ledger
  FOR ALL USING (auth.role() = 'authenticated');

-- ============================================
-- HELPER FUNCTIONS
-- ============================================

-- Belirli bir tarih aralığındaki toplam geliri hesaplama
CREATE OR REPLACE FUNCTION get_total_income(start_date DATE, end_date DATE)
RETURNS NUMERIC AS $$
  SELECT COALESCE(SUM(toplam), 0)
  FROM daily_income
  WHERE date BETWEEN start_date AND end_date;
$$ LANGUAGE SQL;

-- Belirli bir tarih aralığındaki toplam gideri hesaplama
CREATE OR REPLACE FUNCTION get_total_expense(start_date DATE, end_date DATE)
RETURNS NUMERIC AS $$
  SELECT COALESCE(SUM(amount), 0)
  FROM expenses
  WHERE expense_date BETWEEN start_date AND end_date;
$$ LANGUAGE SQL;

-- Belirli bir tarih aralığındaki kar/zarar hesaplama
CREATE OR REPLACE FUNCTION get_profit_loss(start_date DATE, end_date DATE)
RETURNS NUMERIC AS $$
  SELECT get_total_income(start_date, end_date) - get_total_expense(start_date, end_date);
$$ LANGUAGE SQL;
